# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('yearpublished', models.DateField()),
                ('minplayers', models.SmallIntegerField()),
                ('maxplayers', models.SmallIntegerField()),
                ('playtime', models.SmallIntegerField()),
                ('description', models.TextField()),
                ('price', models.SmallIntegerField()),
                ('sale_price', models.SmallIntegerField()),
                ('thumbnail', models.ImageField(upload_to=b'')),
                ('image', models.ImageField(upload_to=b'')),
                ('classic', models.BooleanField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('catagory', models.ManyToManyField(related_name='games', to='store.Catagory')),
            ],
        ),
    ]
