# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20171026_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='yearpublished',
            field=models.SmallIntegerField(),
        ),
    ]
