# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
        ('store', '0003_auto_20171026_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to='login_reg.User')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_orders', to='store.Game')),
            ],
        ),
    ]
