# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.URLField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='game_orders', to='store.Game'),
        ),
    ]
