# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20171026_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='game',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
