# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20171026_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rank',
            field=models.CharField(default='80', max_length=30),
        ),
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.CharField(default='7', max_length=30),
        ),
    ]
