# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20171027_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=30)),
                ('isSale', models.BooleanField(default=False)),
                ('basePrice', models.CharField(max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_price', to='store.Game')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(default='0.00', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedprice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_at_purchase', to='store.Order'),
        ),
    ]
