# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20171028_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rank',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.CharField(max_length=75),
        ),
    ]
