# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20171029_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('price', models.CharField(max_length=30)),
                ('isSale', models.BooleanField(default=False)),
                ('basePrice', models.CharField(max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_price', to='store.Game')),
            ],
        ),
        migrations.RemoveField(
            model_name='savedprice',
            name='game',
        ),
        migrations.RemoveField(
            model_name='savedprice',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.DeleteModel(
            name='SavedPrice',
        ),
        migrations.AddField(
            model_name='iteminorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.Order'),
        ),
    ]
