# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20171029_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminorder',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.Game'),
        ),
    ]
